version: '3.9'

services:
  web:
    restart: always
    container_name: regex
    build: 
      context: ./
      dockerfile: ./services/web/Dockerfile
    command: gunicorn --bind 0.0.0.0:8080 wsgi:app  --timeout 120
    networks:
      - regex
    ports: 
      - 8080:8080
    volumes:
      - /usr/nginx/html
    environment:
      - NODE_ENV=prod

      
networks:
  regex:
    external: 
      name: nlp_project_default